type MonacoThemeData = {
	base: 'vs' | 'vs-dark';
	inherit: boolean;
	rules: { token: string; foreground: string; fontStyle?: string }[];
	colors: Record<string, string>;
};
const dark: MonacoThemeData = {
	base: 'vs-dark',
	inherit: false,
	rules: [
		{ token: '', foreground: 'cdd6f4' },
		{ token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
		{ token: 'comment.doc', foreground: '6c7086', fontStyle: 'italic' },
		{ token: 'string', foreground: 'a6e3a1' },
		{ token: 'string.escape', foreground: 'a6e3a1' },
		{ token: 'keyword', foreground: 'cba6f7', fontStyle: 'bold' },
		{ token: 'keyword.control', foreground: 'cba6f7', fontStyle: 'bold' },
		{ token: 'number', foreground: 'fab387' },
		{ token: 'regexp', foreground: 'f38ba8' },
		{ token: 'type', foreground: '89dceb' },
		{ token: 'class', foreground: '89dceb' },
		{ token: 'function', foreground: '89b4fa' },
		{ token: 'variable', foreground: 'cdd6f4' },
		{ token: 'variable.predefined', foreground: 'f5c2e7' },
		{ token: 'constant', foreground: 'f38ba8' },
		{ token: 'delimiter', foreground: '7f849c' },
		{ token: 'tag', foreground: 'cba6f7' },
		{ token: 'attribute.name', foreground: '89dceb' },
		{ token: 'attribute.value', foreground: 'a6e3a1' },
		{ token: 'metatag', foreground: '7f849c' },
		{ token: 'key', foreground: '89b4fa' }
	],
	colors: {
		'editor.background': '#010207',
		'editor.foreground': '#cdd6f4',
		'editor.selectionBackground': '#767ffa4d',
		'editor.inactiveSelectionBackground': '#101932a6',
		'editor.lineHighlightBackground': '#0c122033',
		'editor.lineHighlightBorder': '#00000000',
		'editorCursor.foreground': '#767ffa',
		'editorLineNumber.foreground': '#6c7086',
		'editorLineNumber.activeForeground': '#cdd6f4',
		'editorIndentGuide.background1': '#1d2842b3',
		'editorIndentGuide.activeBackground1': '#1d28428c',
		'editorBracketMatch.background': '#767ffa1a',
		'editorBracketMatch.border': '#767ffa4d',
		'editorGutter.background': '#010207',
		'editorWidget.background': '#03060dc7',
		'editorWidget.foreground': '#cdd6f4',
		'editorWidget.border': '#1d28428c',
		'editorSuggestWidget.background': '#03060dc7',
		'editorSuggestWidget.border': '#1d28428c',
		'editorSuggestWidget.foreground': '#cdd6f4',
		'editorSuggestWidget.selectedBackground': '#767ffa1a',
		'editorSuggestWidget.selectedForeground': '#cdd6f4',
		'editorSuggestWidget.highlightForeground': '#cba6f7',
		'editorHoverWidget.background': '#03060dc7',
		'editorHoverWidget.border': '#1d28428c',
		'editorHoverWidget.foreground': '#cdd6f4',
		'input.background': '#0f141d8c',
		'input.foreground': '#cdd6f4',
		'input.border': '#1d28428c',
		'input.placeholderForeground': '#6c7086',
		focusBorder: '#767ffa8c',
		'list.hoverBackground': '#101932a6',
		'list.hoverForeground': '#cdd6f4',
		'list.activeSelectionBackground': '#767ffa1a',
		'list.activeSelectionForeground': '#cdd6f4',
		'list.inactiveSelectionBackground': '#0c12204d',
		'list.focusBackground': '#767ffa1a',
		'list.focusForeground': '#cdd6f4',
		'list.highlightForeground': '#cba6f7',
		'scrollbarSlider.background': '#f1f6fc40',
		'scrollbarSlider.hoverBackground': '#f1f6fc4d',
		'scrollbarSlider.activeBackground': '#f1f6fc66',
		'scrollbar.shadow': '#00000000',
		'dropdown.background': '#03060dc7',
		'dropdown.foreground': '#cdd6f4',
		'dropdown.border': '#1d28428c'
	}
};
const light: MonacoThemeData = {
	base: 'vs',
	inherit: false,
	rules: [
		{ token: '', foreground: '4c4f69' },
		{ token: 'comment', foreground: '9ca0b0', fontStyle: 'italic' },
		{ token: 'comment.doc', foreground: '9ca0b0', fontStyle: 'italic' },
		{ token: 'string', foreground: '40a02b' },
		{ token: 'string.escape', foreground: '40a02b' },
		{ token: 'keyword', foreground: '8839ef', fontStyle: 'bold' },
		{ token: 'keyword.control', foreground: '8839ef', fontStyle: 'bold' },
		{ token: 'number', foreground: 'fe640b' },
		{ token: 'regexp', foreground: 'd20f39' },
		{ token: 'type', foreground: '04a5e5' },
		{ token: 'class', foreground: '04a5e5' },
		{ token: 'function', foreground: '1e66f5' },
		{ token: 'variable', foreground: '4c4f69' },
		{ token: 'variable.predefined', foreground: 'ea76cb' },
		{ token: 'constant', foreground: 'd20f39' },
		{ token: 'delimiter', foreground: '9ca0b0' },
		{ token: 'tag', foreground: '8839ef' },
		{ token: 'attribute.name', foreground: '04a5e5' },
		{ token: 'attribute.value', foreground: '40a02b' },
		{ token: 'metatag', foreground: '9ca0b0' },
		{ token: 'key', foreground: '1e66f5' }
	],
	colors: {
		'editor.background': '#eef2f9',
		'editor.foreground': '#4c4f69',
		'editor.selectionBackground': '#5b60d74d',
		'editor.inactiveSelectionBackground': '#cfd8e9b8',
		'editor.lineHighlightBackground': '#dfe5ef33',
		'editor.lineHighlightBorder': '#00000000',
		'editorCursor.foreground': '#5b60d7',
		'editorLineNumber.foreground': '#9ca0b0',
		'editorLineNumber.activeForeground': '#4c4f69',
		'editorIndentGuide.background1': '#bec4d2b3',
		'editorIndentGuide.activeBackground1': '#bec4d2a6',
		'editorBracketMatch.background': '#5b60d71a',
		'editorBracketMatch.border': '#5b60d74d',
		'editorGutter.background': '#eef2f9',
		'editorWidget.background': '#f5f9ffd6',
		'editorWidget.foreground': '#4c4f69',
		'editorWidget.border': '#bec4d2a6',
		'editorSuggestWidget.background': '#f5f9ffd6',
		'editorSuggestWidget.border': '#bec4d2a6',
		'editorSuggestWidget.foreground': '#4c4f69',
		'editorSuggestWidget.selectedBackground': '#5b60d71a',
		'editorSuggestWidget.selectedForeground': '#4c4f69',
		'editorSuggestWidget.highlightForeground': '#8839ef',
		'editorHoverWidget.background': '#f5f9ffd6',
		'editorHoverWidget.border': '#bec4d2a6',
		'editorHoverWidget.foreground': '#4c4f69',
		'input.background': '#d1d8e5a6',
		'input.foreground': '#4c4f69',
		'input.border': '#bec4d2a6',
		'input.placeholderForeground': '#9ca0b0',
		focusBorder: '#5b60d78c',
		'list.hoverBackground': '#cfd8e9b8',
		'list.hoverForeground': '#4c4f69',
		'list.activeSelectionBackground': '#5b60d71a',
		'list.activeSelectionForeground': '#4c4f69',
		'list.inactiveSelectionBackground': '#dfe5ef4d',
		'list.focusBackground': '#5b60d71a',
		'list.focusForeground': '#4c4f69',
		'list.highlightForeground': '#8839ef',
		'scrollbarSlider.background': '#04070f40',
		'scrollbarSlider.hoverBackground': '#04070f4d',
		'scrollbarSlider.activeBackground': '#04070f66',
		'scrollbar.shadow': '#00000000',
		'dropdown.background': '#f5f9ffd6',
		'dropdown.foreground': '#4c4f69',
		'dropdown.border': '#bec4d2a6'
	}
};
export function createMonacoTheme(): MonacoThemeData {
	return document.documentElement.classList.contains('light') ? light : dark;
}
